spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/rest/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: restaurant-service
                fallbackuri: forward:/restFallback

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/cust/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: customer-service
                fallbackuri: forward:/custFallback

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reserv/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: reservation-service
                fallbackuri: forward:/reservFallback

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


